name: Deploy to Prod

on:
  push:
    branches: [ main ]

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to server
          uses: appleboy/ssh-action@master # An action made to control Linux servers
          with: # We set all our secrets here for the action, these won't be shown in the action logs
            host: ${{ secrets.SERVER_ADDRESS }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
              cd ~/cicd-test # we move into our app's folder
              git pull origin main # we pull any changes from git
              npm prune # we remove any unused dependencies
              npm install # we install any missing dependencies
              npm run build # we build our app
              pm2 startOrRestart .ecosystem.config.js --only cicd-test --env production # we deploy the app via PM2